web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes_from:
    - data
db:
  image: aimakun/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: nameyourdb
    MYSQL_ROOT_PASSWORD: provideyourpwd
data:
  image: busybox
  volumes:
    - .:/docker_data